# Module 03 - Data Wrangling with Pandas

---

#### <a href="linkedin.com/in/tasmim-rahman-adib-403074221">Tasmim Rahman Adib</a>

# Lecture 4.7 - Group Data
## Agenda
- Understanding GroupBy objects
- Splitting with many Keys
- split-apply-combine
- Advanced Aggregation with `agg()`
- GroupBy Aggregation with Relabeling
- Transformation with `transform()`
- Replacing NA Values by group-specific Values
- Generalizing split-apply-combine with `apply()`

In [1]:
# conventional import
import pandas as pd

### 4.7.1 Understanding GroupBy objects
---

The "group by" concept: we want to **apply the same function on subsets of your dataframe, based on some key to split the dataframe in subsets**

This operation is also referred to as the "split-apply-combine" operation, involving the following steps:

* **Splitting** the data into groups based on some criteria
* **Applying** a function to each group independently
* **Combining** the results into a data structure

In [4]:
df = pd.read_csv("../data/covid19.csv")
df.head()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   SNo              306429 non-null  int64
 1   ObservationDate  306429 non-null  object
 2   Province/State   228326 non-null  object
 3   Country/Region   306429 non-null  object
 4   Last Update      306429 non-null  object
 5   Confirmed        306429 non-null  float64
 6   Deaths           306429 non-null  float64
 7   Recovered        306429 non-null  float64
dtypes: float64(3), int64(1), object(4)
memory usage: 18.7+ MB

In [7]:
# drop null values
df.dropna(inplace=True)

![](../img/group_by_cities.png)

In [10]:
# group by "Country/Region"
country = df.groupby("Country/Region")

In [15]:
print(list(country))

[('Australia',            SNo ObservationDate     Province/State Country/Region  \
275        276      01/27/2020    New South Wales      Australia
276        277      01/27/2020           Victoria      Australia
328        329      01/28/2020    New South Wales      Australia
329        330      01/28/2020           Victoria      Australia
382        383      01/29/2020    New South Wales      Australia
...        ...             ...                ...            ...
306256  306257      05/29/2021         Queensland      Australia
306317  306318      05/29/2021    South Australia      Australia
306332  306333      05/29/2021           Tasmania      Australia
306392  306393      05/29/2021           Victoria      Australia
306409  306410      05/29/2021  Western Australia      Australia

                Last Update  Confirmed  Deaths  Recovered
275           1/27/20 23:59        4.0     0.0        0.0
276           1/27/20 23:59        1.0     0.0        0.0
328           1/28/20 23:00        4.0     0.0        0.0
329           1/28/20 23:00        1.0     0.0        0.0
382           1/29/20 19:30        4.0     0.0        0.0
...                     ...        ...     ...        ...
306256  2021-05-30 04:20:55     1618.0     7.0     1591.0
306317  2021-05-30 04:20:55      752.0     4.0      746.0
306332  2021-05-30 04:20:55      234.0    13.0      221.0
306392  2021-05-30 04:20:55    20593.0   820.0    19725.0
306409  2021-05-30 04:20:55     1017.0     9.0     1006.0

[3785 rows x 8 columns]), ('Belgium',            SNo ObservationDate   Province/State Country/Region  \
154524  154525      11/12/2020          Antwerp        Belgium
154569  154570      11/12/2020         Brussels        Belgium
154632  154633      11/12/2020    East Flanders        Belgium
154640  154641      11/12/2020  Flemish Brabant        Belgium
154678  154679      11/12/2020          Hainaut        Belgium
...        ...             ...              ...            ...
306118  306119      05/29/2021       Luxembourg        Belgium
306171  306172      05/29/2021            Namur        Belgium
306362  306363      05/29/2021          Unknown        Belgium
306404  306405      05/29/2021  Walloon Brabant        Belgium
306407  306408      05/29/2021    West Flanders        Belgium

                Last Update  Confirmed   Deaths  Recovered
154524  2021-04-02 15:13:53    60560.0      0.0        0.0
154569  2021-04-02 15:13:53    71270.0      0.0        0.0
154632  2021-04-02 15:13:53    46386.0      0.0        0.0
154640  2021-04-02 15:13:53    40227.0      0.0        0.0
154678  2021-04-02 15:13:53    83081.0      0.0        0.0
...                     ...        ...      ...        ...
306118  2021-05-30 04:20:55    30859.0      0.0        0.0
306171  2021-05-30 04:20:55    58543.0      0.0        0.0
306362  2021-05-30 04:20:55    20219.0  24921.0        0.0
306404  2021-05-30 04:20:55    40604.0      0.0        0.0
306407  2021-05-30 04:20:55    95724.0      0.0        0.0

[2388 rows x 8 columns]), ('Brazil',            SNo ObservationDate  Province/State Country/Region  \
27258    27259      05/20/2020            Acre         Brazil
27261    27262      05/20/2020         Alagoas         Brazil
27264    27265      05/20/2020           Amapa         Brazil
27265    27266      05/20/2020        Amazonas         Brazil
27281    27282      05/20/2020           Bahia         Brazil
...        ...             ...             ...            ...
306272  306273      05/29/2021         Roraima         Brazil
306290  306291      05/29/2021  Santa Catarina         Brazil
306292  306293      05/29/2021       Sao Paulo         Brazil
306298  306299      05/29/2021         Sergipe         Brazil
306342  306343      05/29/2021       Tocantins         Brazil

                Last Update  Confirmed    Deaths  Recovered
27258   2021-04-02 15:13:53     2817.0      76.0        0.0
27261   2021-04-02 15:13:53     4437.0     251.0        0.0
27264   2021-04-02 15:13:53     4549.0     142.0        0.0
27265   2021-04-02 15:13:53    23704.0    1561.0        0.0
27281   2021-04-02 15:13:53    11197.0     362.0        0.0
...                     ...        ...       ...        ...
306272  2021-05-30 04:20:55   103222.0    1635.0    96188.0
306290  2021-05-30 04:20:55   965277.0   15174.0   921496.0
306292  2021-05-30 04:20:55  3254893.0  111123.0  2895697.0
306298  2021-05-30 04:20:55   233932.0    5054.0   208146.0
306342  2021-05-30 04:20:55   177464.0    2852.0   159306.0

[10144 rows x 8 columns]), ('Canada',            SNo ObservationDate          Province/State Country/Region  \
223        224      01/26/2020                 Ontario         Canada
271        272      01/27/2020                 Ontario         Canada
324        325      01/28/2020                 Ontario         Canada
325        326      01/28/2020        British Columbia         Canada
378        379      01/29/2020                 Ontario         Canada
...        ...             ...                     ...            ...
306244  306245      05/29/2021    Prince Edward Island         Canada
306255  306256      05/29/2021                  Quebec         Canada
306262  306263      05/29/2021  Repatriated Travellers         Canada
306295  306296      05/29/2021            Saskatchewan         Canada
306419  306420      05/29/2021                   Yukon         Canada

                Last Update  Confirmed   Deaths  Recovered
223           1/26/20 16:00        1.0      0.0        0.0
271           1/27/20 23:59        1.0      0.0        0.0
324           1/28/20 23:00        1.0      0.0        0.0
325           1/28/20 23:00        1.0      0.0        0.0
378           1/29/20 19:30        1.0      0.0        0.0
...                     ...        ...      ...        ...
306244  2021-05-30 04:20:55      200.0      0.0      187.0
306255  2021-05-30 04:20:55   369728.0  11125.0   354104.0
306262  2021-05-30 04:20:55       13.0      0.0       13.0
306295  2021-05-30 04:20:55    46464.0    537.0    44519.0
306419  2021-05-30 04:20:55       84.0      2.0       82.0

[6960 rows x 8 columns]), ('Chile',            SNo ObservationDate      Province/State Country/Region  \
27269    27270      05/20/2020         Antofagasta          Chile
27271    27272      05/20/2020           Araucania          Chile
27272    27273      05/20/2020  Arica y Parinacota          Chile
27277    27278      05/20/2020             Atacama          Chile
27279    27280      05/20/2020               Aysen          Chile
...        ...             ...                 ...            ...
306206  306207      05/29/2021               Nuble          Chile
306209  306210      05/29/2021            OHiggins          Chile
306331  306332      05/29/2021            Tarapaca          Chile
306363  306364      05/29/2021             Unknown          Chile
306381  306382      05/29/2021          Valparaiso          Chile

                Last Update  Confirmed  Deaths  Recovered
27269   2021-04-02 15:13:53     1731.0    17.0        0.0
27271   2021-04-02 15:13:53     1680.0    44.0        0.0
27272   2021-04-02 15:13:53      424.0     7.0        0.0
27277   2021-04-02 15:13:53      163.0     0.0        0.0
27279   2021-04-02 15:13:53        8.0     0.0        0.0
...                     ...        ...     ...        ...
306206  2021-05-30 04:20:55    29947.0   502.0    28355.0
306209  2021-05-30 04:20:55    56389.0  1153.0    53054.0
306331  2021-05-30 04:20:55    36665.0   668.0    35418.0
306363  2021-05-30 04:20:55       54.0     0.0       54.0
306381  2021-05-30 04:20:55    97830.0  2566.0    92035.0

[6375 rows x 8 columns]), ('China',        SNo ObservationDate Province/State Country/Region          Last Update  \
38      39      01/22/2020        Unknown          China      1/22/2020 17:00
86      87      01/23/2020        Unknown          China        1/23/20 17:00
129    130      01/24/2020        Unknown          China        1/24/20 17:00
175    176      01/25/2020        Unknown          China        1/25/20 17:00
224    225      01/26/2020        Unknown          China        1/26/20 16:00
277    278      01/27/2020        Unknown          China        1/27/20 23:59
331    332      01/28/2020        Unknown          China        1/28/20 23:00
387    388      01/29/2020        Unknown          China        1/29/20 19:30
447    448      01/30/2020        Unknown          China        1/30/20 16:00
511    512      01/31/2020        Unknown          China      1/31/2020 23:59
580    581      02/01/2020        Unknown          China       2/1/2020 11:53
649    650      02/02/2020        Unknown          China  2020-02-02T23:43:02
719    720      02/03/2020        Unknown          China  2020-02-03T23:23:03
791    792      02/04/2020        Unknown          China  2020-02-04T23:43:01
864    865      02/05/2020        Unknown          China  2020-02-05T23:13:12
937    938      02/06/2020        Unknown          China  2020-02-06T23:23:02
1011  1012      02/07/2020        Unknown          China  2020-02-07T23:43:02
1085  1086      02/08/2020        Unknown          China  2020-02-08T23:33:06
1159  1160      02/09/2020        Unknown          China  2020-02-09T23:33:02
1233  1234      02/10/2020        Unknown          China  2020-02-10T23:33:02
1308  1309      02/11/2020        Unknown          China  2020-02-11T23:33:02
1383  1384      02/12/2020        Unknown          China  2020-02-12T14:13:08
1459  1460      02/13/2020        Unknown          China  2020-02-13T14:13:06
1536  1537      02/14/2020        Unknown          China  2020-02-14T23:33:02
1613  1614      02/15/2020        Unknown          China  2020-02-15T23:13:05
1690  1691      02/16/2020        Unknown          China  2020-02-16T23:53:01
1767  1768      02/17/2020        Unknown          China  2020-02-17T23:13:06
1844  1845      02/18/2020        Unknown          China  2020-02-18T23:13:11
1922  1923      02/19/2020        Unknown          China  2020-02-19T23:23:02
2000  2001      02/20/2020        Unknown          China  2020-02-20T23:43:02
2086  2087      02/21/2020        Unknown          China  2020-02-21T13:03:09
2172  2173      02/22/2020        Unknown          China  2020-02-22T23:33:06
2259  2260      02/23/2020        Unknown          China  2020-02-23T11:33:03
2351  2352      02/24/2020        Unknown          China  2020-02-24T11:13:09
2447  2448      02/25/2020        Unknown          China  2020-02-25T15:23:04
2550  2551      02/26/2020        Unknown          China  2020-02-26T14:13:10
2657  2658      02/27/2020        Unknown          China  2020-02-27T12:13:14
2773  2774      02/28/2020        Unknown          China  2020-02-28T00:43:01
2894  2895      02/29/2020        Unknown          China  2020-02-29T12:13:10
3021  3022      03/01/2020        Unknown          China  2020-03-01T10:13:19
3164  3165      03/02/2020        Unknown          China  2020-03-02T15:03:23
3317  3318      03/03/2020        Unknown          China  2020-03-03T11:43:02
3479  3480      03/04/2020        Unknown          China  2020-03-04T12:53:03
3654  3655      03/05/2020        Unknown          China  2020-03-05T14:53:03
3855  3856      03/06/2020        Unknown          China  2020-03-06T14:23:04
4082  4083      03/07/2020        Unknown          China  2020-03-07T11:13:04
4339  4340      03/08/2020        Unknown          China  2020-03-08T14:43:03
4607  4608      03/09/2020        Unknown          China  2020-03-09T14:33:03

      Confirmed  Deaths  Recovered
38          0.0     0.0        0.0
86          0.0     0.0        0.0
129         0.0     0.0        0.0
175         0.0     0.0        0.0
224         0.0     0.0        0.0
277         0.0     0.0        0.0
331         0.0     0.0        0.0
387         0.0     0.0        0.0
447         0.0     0.0        0.0
511         0.0     0.0        0.0
580         0.0     0.0        0.0
649         0.0     0.0        0.0
719         0.0     0.0        0.0
791         0.0     0.0        0.0
864         0.0     0.0        0.0
937         0.0     0.0        0.0
1011        0.0     0.0        0.0
1085        0.0     0.0        0.0
1159        0.0     0.0        0.0
1233        0.0     0.0        0.0
1308        0.0     0.0        0.0
1383        0.0     0.0        0.0
1459        0.0     0.0        0.0
1536        0.0     0.0        0.0
1613        0.0     0.0        0.0
1690        0.0     0.0        0.0
1767        0.0     0.0        0.0
1844        0.0     0.0        0.0
1922        0.0     0.0        0.0
2000        0.0     0.0        0.0
2086        0.0     0.0        0.0
2172        0.0     0.0        0.0
2259        0.0     0.0        0.0
2351        0.0     0.0        0.0
2447        0.0     0.0        0.0
2550        0.0     0.0        0.0
2657        0.0     0.0        0.0
2773        0.0     0.0        0.0
2894        0.0     0.0        0.0
3021        0.0     0.0        0.0
3164        0.0     0.0        0.0
3317        0.0     0.0        0.0
3479        0.0     0.0        0.0
3654        0.0     0.0        0.0
3855        0.0     0.0        0.0
4082        0.0     0.0        0.0
4339        0.0     0.0        0.0
4607        0.0     0.0        0.0  ), ('Colombia',            SNo ObservationDate   Province/State Country/Region  \
30913    30914      05/28/2020         Amazonas       Colombia
30919    30920      05/28/2020        Antioquia       Colombia
30924    30925      05/28/2020           Arauca       Colombia
30933    30934      05/28/2020        Atlantico       Colombia
30948    30949      05/28/2020          Bolivar       Colombia
...        ...             ...              ...            ...
306346  306347      05/29/2021           Tolima       Colombia
306364  306365      05/29/2021          Unknown       Colombia
306380  306381      05/29/2021  Valle del Cauca       Colombia
306387  306388      05/29/2021           Vaupes       Colombia
306391  306392      05/29/2021          Vichada       Colombia

                Last Update  Confirmed  Deaths  Recovered
30913   2021-04-02 15:13:53     1723.0    57.0      120.0
30919   2021-04-02 15:13:53      960.0     6.0      405.0
30924   2021-04-02 15:13:53        1.0     0.0        0.0
30933   2021-04-02 15:13:53     3114.0    81.0      330.0
30948   2021-04-02 15:13:53     2516.0   125.0      361.0
...                     ...        ...     ...        ...
306346  2021-05-30 04:20:55    75296.0  2432.0    71624.0
306364  2021-05-30 04:20:55        0.0     0.0        0.0
306380  2021-05-30 04:20:55   266414.0  8461.0   251388.0
306387  2021-05-30 04:20:55     1528.0    14.0     1481.0
306391  2021-05-30 04:20:55     1772.0    25.0     1727.0

[12419 rows x 8 columns]), ('Denmark',            SNo ObservationDate Province/State Country/Region  \
4842      4843      03/11/2020        Denmark        Denmark
4986      4987      03/11/2020  Faroe Islands        Denmark
5054      5055      03/12/2020        Denmark        Denmark
5207      5208      03/12/2020  Faroe Islands        Denmark
5340      5341      03/13/2020        Denmark        Denmark
...        ...             ...            ...            ...
304471  304472      05/27/2021      Greenland        Denmark
305211  305212      05/28/2021  Faroe Islands        Denmark
305236  305237      05/28/2021      Greenland        Denmark
305976  305977      05/29/2021  Faroe Islands        Denmark
306001  306002      05/29/2021      Greenland        Denmark

                Last Update  Confirmed  Deaths  Recovered
4842    2020-03-11T22:13:13      442.0     0.0        1.0
4986    2020-03-11T20:53:02        2.0     0.0        0.0
5054    2020-03-12T09:53:06      615.0     0.0        1.0
5207    2020-03-11T20:53:02        2.0     0.0        0.0
5340    2020-03-11T20:00:00      801.0     0.0        1.0
...                     ...        ...     ...        ...
304471  2021-05-28 04:20:36       36.0     0.0       33.0
305211  2021-05-29 04:20:41      707.0     1.0      669.0
305236  2021-05-29 04:20:41       36.0     0.0       33.0
305976  2021-05-30 04:20:55      712.0     1.0      669.0
306001  2021-05-30 04:20:55       37.0     0.0       33.0

[893 rows x 8 columns]), ('France',            SNo ObservationDate             Province/State Country/Region  \
4821      4822      03/11/2020                     France         France
4987      4988      03/11/2020                  St Martin         France
5003      5004      03/11/2020           Saint Barthelemy         France
5039      5040      03/12/2020                     France         France
5208      5209      03/12/2020                  St Martin         France
...        ...             ...                        ...            ...
306263  306264      05/29/2021                    Reunion         France
306279  306280      05/29/2021           Saint Barthelemy         France
306282  306283      05/29/2021  Saint Pierre and Miquelon         France
306320  306321      05/29/2021                  St Martin         France
306403  306404      05/29/2021          Wallis and Futuna         France

                Last Update  Confirmed  Deaths  Recovered
4821    2020-03-11T22:53:03     2281.0    48.0       12.0
4987    2020-03-11T20:53:02        2.0     0.0        0.0
5003    2020-03-11T20:53:02        1.0     0.0        0.0
5039    2020-03-11T22:53:03     2281.0    48.0       12.0
5208    2020-03-11T20:53:02        2.0     0.0        0.0
...                     ...        ...     ...        ...
306263  2021-05-30 04:20:55    24901.0   189.0    22796.0
306279  2021-05-30 04:20:55     1005.0     1.0      462.0
306282  2021-05-30 04:20:55       25.0     0.0       25.0
306320  2021-05-30 04:20:55     1915.0    12.0     1399.0
306403  2021-05-30 04:20:55      445.0     7.0      438.0

[4544 rows x 8 columns]), ('Germany',            SNo ObservationDate      Province/State Country/Region  \
330        331      01/28/2020             Bavaria        Germany
384        385      01/29/2020             Bavaria        Germany
442        443      01/30/2020             Bavaria        Germany
489        490      01/31/2020             Bavaria        Germany
24986    24987      05/14/2020   Baden-Wurttemberg        Germany
...        ...             ...                 ...            ...
306276  306277      05/29/2021             Sachsen        Germany
306277  306278      05/29/2021      Sachsen-Anhalt        Germany
306296  306297      05/29/2021  Schleswig-Holstein        Germany
306338  306339      05/29/2021           Thuringen        Germany
306365  306366      05/29/2021             Unknown        Germany

                Last Update  Confirmed  Deaths  Recovered
330           1/28/20 23:00        4.0     0.0        0.0
384           1/29/20 19:30        4.0     0.0        0.0
442           1/30/20 16:00        4.0     0.0        0.0
489         1/31/2020 23:59        5.0     0.0        0.0
24986   2021-04-02 15:13:53    33804.0  1629.0    29400.0
...                     ...        ...     ...        ...
306276  2021-05-30 04:20:55   283612.0  9675.0   262800.0
306277  2021-05-30 04:20:55    98406.0  3317.0    92000.0
306296  2021-05-30 04:20:55    63017.0  1593.0    60000.0
306338  2021-05-30 04:20:55   127481.0  4202.0   120100.0
306365  2021-05-30 04:20:55     5126.0     0.0        0.0

[6481 rows x 8 columns]), ('Hong Kong',            SNo ObservationDate Province/State Country/Region  \
12          13      01/22/2020      Hong Kong      Hong Kong
52          53      01/23/2020      Hong Kong      Hong Kong
113        114      01/24/2020      Hong Kong      Hong Kong
155        156      01/25/2020      Hong Kong      Hong Kong
200        201      01/26/2020      Hong Kong      Hong Kong
...        ...             ...            ...            ...
302968  302969      05/25/2021      Hong Kong      Hong Kong
303733  303734      05/26/2021      Hong Kong      Hong Kong
304498  304499      05/27/2021      Hong Kong      Hong Kong

In [34]:
# get number of unique group
country.nunique()

,SNo,ObservationDate,Province/State,Last Update,Confirmed,Deaths,Recovered
Country/Region,,,,,,,
Australia,3785,489,12,163,1415,129,954
Belgium,2388,199,12,59,2342,198,1
Brazil,10144,375,28,59,9780,6860,5930
Canada,6960,490,22,185,2944,1544,2629
Chile,6375,375,17,59,5590,1546,5077
China,48,48,1,48,1,1,1
Colombia,12419,367,34,59,9465,3271,8975
Denmark,893,445,3,119,187,8,153
France,4544,445,13,128,1149,169,385
Germany,6481,385,18,63,5896,2857,4773
Hong Kong,494,494,1,159,441,126,432
India,13050,354,38,59,11494,5198,11261
Israel,5,5,1,2,1,1,1
Italy,8001,381,21,59,7151,3849,6973
Japan,17932,367,49,59,6449,999,5720
Macau,494,494,1,130,30,1,36
Mainland China,15758,494,32,885,1685,97,1670
Mexico,12199,375,33,59,10933,6006,5111
Netherlands,5864,440,18,113,4650,1656,796
Others,46,46,2,25,16,7,6
Pakistan,2478,354,7,59,2333,1352,2269
Peru,9542,367,26,59,6573,2492,285
Russia,30129,363,83,59,22248,3281,21165
Spain,7615,381,20,59,4821,2587,75
Sweden,7539,359,21,59,3921,855,1
Taiwan,49,49,1,37,28,2,10
UK,6553,445,19,125,2343,1122,792
US,26740,494,199,395,20889,9447,276
Ukraine,9801,363,27,59,8682,2231,7714

In [26]:
# count rows for each groups
country.count()

,SNo,ObservationDate,Province/State,Last Update,Confirmed,Deaths,Recovered
Country/Region,,,,,,,
Australia,3785,3785,3785,3785,3785,3785,3785
Belgium,2388,2388,2388,2388,2388,2388,2388
Brazil,10144,10144,10144,10144,10144,10144,10144
Canada,6960,6960,6960,6960,6960,6960,6960
Chile,6375,6375,6375,6375,6375,6375,6375
China,48,48,48,48,48,48,48
Colombia,12419,12419,12419,12419,12419,12419,12419
Denmark,893,893,893,893,893,893,893
France,4544,4544,4544,4544,4544,4544,4544
Germany,6481,6481,6481,6481,6481,6481,6481
Hong Kong,494,494,494,494,494,494,494
India,13050,13050,13050,13050,13050,13050,13050
Israel,5,5,5,5,5,5,5
Italy,8001,8001,8001,8001,8001,8001,8001
Japan,17932,17932,17932,17932,17932,17932,17932
Macau,494,494,494,494,494,494,494
Mainland China,15758,15758,15758,15758,15758,15758,15758
Mexico,12199,12199,12199,12199,12199,12199,12199
Netherlands,5864,5864,5864,5864,5864,5864,5864
Others,46,46,46,46,46,46,46
Pakistan,2478,2478,2478,2478,2478,2478,2478
Peru,9542,9542,9542,9542,9542,9542,9542
Russia,30129,30129,30129,30129,30129,30129,30129
Spain,7615,7615,7615,7615,7615,7615,7615
Sweden,7539,7539,7539,7539,7539,7539,7539
Taiwan,49,49,49,49,49,49,49
UK,6553,6553,6553,6553,6553,6553,6553
US,26740,26740,26740,26740,26740,26740,26740
Ukraine,9801,9801,9801,9801,9801,9801,9801

In [29]:
# get each group's max value
country.max()

,SNo,ObservationDate,Province/State,Last Update,Confirmed,Deaths,Recovered
Country/Region,,,,,,,
Australia,306410,12/31/2020,Western Australia,4/6/20 9:37,20593.0,820.0,19725.0
Belgium,306408,12/31/2020,West Flanders,2021-05-30 04:20:55,156458.0,24921.0,0.0
Brazil,306343,12/31/2020,Unknown,2021-05-30 04:20:55,3254893.0,111123.0,2895697.0
Canada,306420,12/31/2020,Yukon,4/6/20 9:37,537138.0,11125.0,515505.0
Chile,306382,12/31/2020,Valparaiso,2021-05-30 04:20:55,569995.0,15354.0,534926.0
China,4608,03/09/2020,Unknown,2020-03-09T14:33:03,0.0,0.0,0.0
Colombia,306392,12/31/2020,Vichada,2021-05-30 04:20:55,951083.0,18683.0,869117.0
Denmark,306002,12/31/2020,Greenland,4/6/20 9:37,1326.0,13.0,669.0
France,306404,12/31/2020,Wallis and Futuna,4/6/20 9:37,24901.0,860.0,22796.0
Germany,306366,12/31/2020,Unknown,2021-05-30 04:20:55,804733.0,16717.0,759500.0
Hong Kong,306029,12/31/2020,Hong Kong,4/6/20 9:37,11837.0,210.0,11571.0
India,306407,12/31/2020,West Bengal,2021-05-30 04:20:55,5713215.0,94030.0,5339838.0
Israel,2429,02/25/2020,From Diamond Princess,2020-02-22T20:53:02,1.0,0.0,0.0
Italy,306389,12/31/2020,Veneto,2021-05-30 04:20:55,834527.0,33593.0,768559.0
Japan,306417,12/31/2020,Yamanashi,2021-05-30 04:20:55,160315.0,2287.0,152231.0
Macau,306121,12/31/2020,Macau,4/6/20 9:37,51.0,0.0,49.0
Mainland China,306427,12/31/2020,Zhejiang,4/6/20 9:37,68159.0,4512.0,64435.0
Mexico,306423,12/31/2020,Zacatecas,2021-05-30 04:20:55,657832.0,34955.0,1924865.0
Netherlands,306429,12/31/2020,Zuid-Holland,4/6/20 9:37,391559.0,4252.0,12121.0
Others,8226,03/23/2020,Diamond Princess cruise ship,3/8/20 5:31,712.0,8.0,567.0
Pakistan,306312,12/31/2020,Sindh,2021-05-30 04:20:55,339073.0,9982.0,308733.0
Peru,306372,12/31/2020,Unknown,2021-05-30 04:20:55,878346.0,29722.0,1897522.0
Russia,306422,12/31/2020,Zabaykalsky Krai,2021-05-30 04:20:55,1173637.0,20001.0,1058041.0
Spain,306373,12/31/2020,Unknown,2021-05-30 04:20:55,714616.0,15285.0,150376.0
Sweden,306387,12/31/2020,Vastra Gotaland,2021-05-30 04:20:55,251285.0,4320.0,0.0
Taiwan,4674,03/10/2020,Taiwan,2020-03-10T19:13:15,47.0,1.0,17.0
UK,306403,12/31/2020,Wales,4/6/20 9:37,3910803.0,112385.0,4192.0
US,306412,12/31/2020,"Yolo County, CA",4/6/20 9:37,3788713.0,63236.0,6399531.0
Ukraine,306428,12/31/2020,Zhytomyr Oblast,2021-05-30 04:20:55,206278.0,5076.0,163588.0

In [32]:
# get min for each group
country.min()

,SNo,ObservationDate,Province/State,Last Update,Confirmed,Deaths,Recovered
Country/Region,,,,,,,
Australia,276,01/01/2021,Australian Capital Territory,1/27/20 23:59,0.0,0.0,0.0
Belgium,154525,01/01/2021,Antwerp,2021-04-02 15:13:53,8595.0,0.0,0.0
Brazil,27259,01/01/2021,Acre,2021-04-02 15:13:53,0.0,0.0,0.0
Canada,224,01/01/2021,"Montreal, QC",1/26/20 16:00,0.0,0.0,0.0
Chile,27270,01/01/2021,Antofagasta,2021-04-02 15:13:53,0.0,0.0,0.0
China,39,01/22/2020,Unknown,1/22/2020 17:00,0.0,0.0,0.0
Colombia,30914,01/01/2021,Amazonas,2021-04-02 15:13:53,-302844.0,-178.0,-854405.0
Denmark,4843,01/01/2021,Denmark,2020-03-11T20:00:00,2.0,0.0,0.0
France,4822,01/01/2021,Fench Guiana,2020-03-11T20:00:00,0.0,0.0,0.0
Germany,331,01/01/2021,Baden-Wurttemberg,1/28/20 23:00,4.0,0.0,0.0
Hong Kong,13,01/01/2021,Hong Kong,1/22/2020 17:00,0.0,0.0,0.0
India,39261,01/01/2021,Andaman and Nicobar Islands,2021-04-02 15:13:53,0.0,0.0,0.0
Israel,2072,02/21/2020,From Diamond Princess,2020-02-21T15:33:03,1.0,0.0,0.0
Italy,24974,01/01/2021,Abruzzo,2021-04-02 15:13:53,389.0,22.0,152.0
Japan,30906,01/01/2021,Aichi,2021-04-02 15:13:53,0.0,0.0,0.0
Macau,21,01/01/2021,Macau,1/22/2020 17:00,1.0,0.0,0.0
Mainland China,1,01/01/2021,Anhui,1/22/2020 17:00,0.0,0.0,0.0
Mexico,27260,01/01/2021,Aguascalientes,2021-04-02 15:13:53,0.0,0.0,0.0
Netherlands,6008,01/01/2021,Aruba,2020-03-16T00:22:11,1.0,0.0,0.0
Others,966,02/07/2020,Cruise Ship,2020-02-07T16:33:03,61.0,0.0,0.0
Pakistan,39287,01/01/2021,Azad Jammu and Kashmir,2021-04-02 15:13:53,444.0,9.0,217.0
Peru,30915,01/01/2021,Amazonas,2021-04-02 15:13:53,0.0,0.0,0.0
Russia,33136,01/01/2021,Adygea Republic,2021-04-02 15:13:53,73.0,0.0,12.0
Spain,24978,01/01/2021,Andalusia,2021-04-02 15:13:53,0.0,0.0,0.0
Sweden,35858,01/01/2021,Blekinge,2021-04-02 15:13:53,88.0,5.0,0.0
Taiwan,29,01/22/2020,Taiwan,1/22/2020 17:00,1.0,0.0,0.0
UK,4842,01/01/2021,Anguilla,2020-03-11T20:00:00,0.0,0.0,0.0
US,32,01/01/2021,"Norfolk County, MA",1/22/2020 17:00,0.0,0.0,0.0
Ukraine,33221,01/01/2021,Cherkasy Oblast,2021-04-02 15:13:53,47.0,0.0,40.0

In [33]:
# describe all statistics for each group
country.describe()

                    SNo                                                    \
                  count           mean           std       min        25%
Country/Region
Australia        3785.0  132539.031440  95479.519274     276.0   38857.00
Belgium          2388.0  230402.476968  43928.899647  154525.0  192353.25
Brazil          10144.0  163760.847299  81800.900294   27259.0   92596.75
Canada           6960.0  141273.261494  93564.856224     224.0   52774.50
Chile            6375.0  163960.914980  81678.859888   27270.0   92842.50
China              48.0    1748.125000   1248.349491      39.0     702.50
Colombia        12419.0  167325.590547  79999.324754   30914.0   97798.50
Denmark           893.0  140084.861142  92662.416563    4843.0   53300.00
France           4544.0  145793.008363  92552.099652    4822.0   59481.50
Germany          6481.0  161734.092887  82907.224569     331.0   89550.00
Hong Kong         494.0  126796.010121  97163.839341      13.0   29298.00
India           13050.0  172217.293103  77159.027321   39261.0  105421.25
Israel              5.0    2247.200000    140.601209    2072.0    2158.00
Italy            8001.0  161857.106487  82836.099487   24974.0   89639.00
Japan           17932.0  167316.266395  79926.671114   30906.0   98027.75
Macau             494.0  126868.574899  97185.906390      21.0   29321.00
Mainland China  15758.0  127277.607374  96995.488686       1.0   29763.25
Mexico          12199.0  165101.282318  81640.411267   27260.0   94120.00
Netherlands      5864.0  173159.483117  79017.997580    6008.0  109779.00
Others             46.0    3504.521739   2098.625495     966.0    1798.75
Pakistan         2478.0  171743.345843  77347.348716   39287.0  104629.25
Peru             9542.0  166916.664326  80066.013713   30915.0   97354.00
Russia          30129.0  168464.728866  79232.865886   33136.0   99634.00
Spain            7615.0  161811.956796  82782.411924   24978.0   89581.50
Sweden           7539.0  169996.234912  78396.481282   35858.0  101961.00
Taiwan             49.0    1752.714286   1268.019601      29.0     688.00
UK               6553.0  151291.644590  88621.023211    4842.0   73577.00
US              26740.0  135883.324757  94285.388467      32.0   45260.00
Ukraine          9801.0  168474.085808  79235.762050   33221.0   99672.00

                                              Confirmed                 ...  \
                     50%        75%       max     count           mean  ...
Country/Region                                                          ...
Australia       126475.0  216063.00  306410.0    3785.0    2496.018494  ...
Belgium         230373.5  268487.00  306408.0    2388.0   64796.513819  ...
Brazil          162912.5  234700.25  306343.0   10144.0  261168.712145  ...
Canada          139123.0  223412.75  306420.0    6960.0   27801.370259  ...
Chile           163161.0  234735.00  306382.0    6375.0   36326.458510  ...
China             1575.5    2577.75    4608.0      48.0       0.000000  ...
Colombia        166801.0  236610.00  306392.0   12419.0   41453.977857  ...
Denmark         135943.0  221062.00  306002.0     893.0     237.655095  ...
France          144327.5  227485.75  306404.0    4544.0    4221.972051  ...
Germany         160783.0  233601.00  306366.0    6481.0   79838.925012  ...
Hong Kong       118407.5  211742.75  306029.0     494.0    5376.386640  ...
India           171600.0  239005.75  306407.0   13050.0  246826.834100  ...
Israel            2244.0    2333.00    2429.0       5.0       1.000000  ...
Italy           160917.0  233620.00  306389.0    8001.0   78459.479565  ...
Japan           166700.5  236544.50  306417.0   17932.0    4944.571437  ...
Macau           118496.5  211834.75  306121.0     494.0      41.710526  ...
Mainland China  119053.0  212267.00  306427.0   15758.0    2590.594999  ...
Mexico          165274.0  235829.50  306423.0   12199.0   37671.717272  ...
Netherlands     174640.5  240537.50  306429.0    5864.0   39290.729536  ...
Others            2847.0    4996.25    8226.0      46.0     570.173913  ...
Pakistan        171153.0  238713.50  306312.0    2478.0   65877.978612  ...
Peru            166197.0  236299.00  306372.0    9542.0   37569.651645  ...
Russia          167784.0  237214.00  306422.0   30129.0   30573.535298  ...
Spain           160748.0  233480.00  306373.0    7615.0   84061.982928  ...
Sweden          169369.0  237950.00  306387.0    7539.0   18672.474997  ...
Taiwan            1576.0    2595.00    4674.0      49.0      22.530612  ...
UK              150092.0  228130.00  306403.0    6553.0  117585.465436  ...
US              130854.5  218263.50  306412.0   26740.0  226220.855161  ...
Ukraine         167740.0  237198.00  306428.0    9801.0   31652.492093  ...

                 Deaths           Recovered                                \
                    75%       max     count           mean            std
Country/Region
Australia         13.00     820.0    3785.0    1907.512021    4977.259758
Belgium            0.00   24921.0    2388.0       0.000000       0.000000
Brazil          7990.50  111123.0   10144.0  227917.318809  316313.844486
Canada           203.00   11125.0    6960.0   24651.853879   68084.270241
Chile            568.50   15354.0    6375.0   33988.522196   73367.992793
China              0.00       0.0      48.0       0.000000       0.000000
Colombia        1188.50   18683.0   12419.0   37735.566229   90045.542671
Denmark            0.00      13.0     893.0     216.023516     248.443167
France            47.00     860.0    4544.0    2065.084727    3763.127654
Germany         2627.00   16717.0    6481.0   69328.294708  117900.000969
Hong Kong        172.50     210.0     494.0    4926.271255    4159.803047
India           3243.25   94030.0   13050.0  222088.742835  426206.634873
Israel             0.00       0.0       5.0       0.000000       0.000000
Italy           3783.00   33593.0    8001.0   60636.714411  107663.714946
Japan             63.00    2287.0   17932.0    4352.779723   12677.312101
Macau              0.00       0.0     494.0      38.724696      15.224391
Mainland China     6.00    4512.0   15758.0    2341.505331   10480.074468
Mexico          4206.00   34955.0   12199.0   29612.280761  190057.061060
Netherlands      947.25    4252.0    5864.0     561.950887    1836.164308
Others             7.00       8.0      46.0     108.760870     167.969995
Pakistan        2226.00    9982.0    2478.0   58641.004036   73040.729852
Peru            1392.00   29722.0    9542.0   33822.723014  196565.870085
Russia           526.00   20001.0   30129.0   26165.072920   72760.410748
Spain           3034.50   15285.0    7615.0    7521.050689   10753.710991
Sweden           332.00    4320.0    7539.0       0.000000       0.000000
Taiwan             1.00       1.0      49.0       3.857143       4.924429
UK                83.00  112385.0    6553.0     354.613307     851.334792
US              5353.75   63236.0   26740.0   18824.643082  251221.750826
Ukraine          902.00    5076.0    9801.0   23900.397102   28296.826683


                     min       25%       50%        75%        max
Country/Region
Australia            0.0     38.00     221.0     946.00    19725.0
Belgium              0.0      0.00       0.0       0.00        0.0
Brazil               0.0  55699.00  136447.0  269142.00  2895697.0
Canada               0.0      5.00     222.5    6855.00   515505.0
Chile                0.0   3154.50   12886.0   27365.50   534926.0
China                0.0      0.00       0.0       0.00        0.0
Colombia       -854405.0   1280.50    9757.0   37467.00   869117.0
Denmark              0.0     14.00      31.0     472.00      669.0
France               0.0     28.00     127.0    2375.00    22796.0
Germany              0.0   4700.00   21030.0   72307.00   759500.0
Hong Kong            0.0   1030.00    4761.5    9089.75    11571.0
India                0.0   5783.75   44043.5  261162.25  5339838.0
Israel               0.0      0.00       0.0       0.00        0.0
Italy              152.0   3933.00   16438.0   64806.00   768559.0
Japan                0.0    161.00     651.0    2549.50   152231.0
Macau                0.0     45.00      46.0      46.00       49.0
Mainland China       0.0    153.00     365.0     935.00    64435.0
Mexico               0.0      0.00       0.0    6746.00  1924865.0
Netherlands          0.0      0.00       0.0      13.00    12121.0
Others               0.0      0.00      10.0     325.00      567.0
Pakistan           217.0   7433.00   20650.0   92552.00   308733.0
Peru                 0.0      0.00       0.0       0.00  1897522.0
Russia              12.0   4824.00   12767.0   28295.00  1058041.0
Spain                0.0   1533.00    3107.0    9204.00   150376.0
Sweden               0.0      0.00       0.0       0.00        0.0
Taiwan               0.0      0.00       2.0       5.00       17.0
UK                   0.0      0.00      13.0     271.00     4192.0
US                   0.0      0.00       0.0       0.00  6399531.0
Ukraine             40.0   1555.00   10292.0   41122.00   163588.0

[29 rows x 32 columns]

In [30]:
#  get data for individual group
country.get_group("Brazil")

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
27258,27259,05/20/2020,Acre,Brazil,2021-04-02 15:13:53,2817.0,76.0,0.0
27261,27262,05/20/2020,Alagoas,Brazil,2021-04-02 15:13:53,4437.0,251.0,0.0
27264,27265,05/20/2020,Amapa,Brazil,2021-04-02 15:13:53,4549.0,142.0,0.0
27265,27266,05/20/2020,Amazonas,Brazil,2021-04-02 15:13:53,23704.0,1561.0,0.0
27281,27282,05/20/2020,Bahia,Brazil,2021-04-02 15:13:53,11197.0,362.0,0.0
...,...,...,...,...,...,...,...,...
306272,306273,05/29/2021,Roraima,Brazil,2021-05-30 04:20:55,103222.0,1635.0,96188.0
306290,306291,05/29/2021,Santa Catarina,Brazil,2021-05-30 04:20:55,965277.0,15174.0,921496.0
306292,306293,05/29/2021,Sao Paulo,Brazil,2021-05-30 04:20:55,3254893.0,111123.0,2895697.0
306298,306299,05/29/2021,Sergipe,Brazil,2021-05-30 04:20:55,233932.0,5054.0,208146.0
306342,306343,05/29/2021,Tocantins,Brazil,2021-05-30 04:20:55,177464.0,2852.0,159306.0

### 4.7.2 Splitting with many Keys

In [35]:
split_with_many_keys = df.groupby(by = ["Country/Region", "Province/State"])

In [36]:
split_with_many_keys.count()

                                             SNo  ObservationDate  \
Country/Region Province/State
Australia      Australian Capital Territory  443              443
               Diamond Princess cruise ship   12               12
               External territories            1                1
               From Diamond Princess          18               18
               Jervis Bay Territory            1                1
...                                          ...              ...
Ukraine        Vinnytsia Oblast              363              363
               Volyn Oblast                  363              363
               Zakarpattia Oblast            363              363
               Zaporizhia Oblast             363              363
               Zhytomyr Oblast               363              363

                                             Last Update  Confirmed  Deaths  \
Country/Region Province/State
Australia      Australian Capital Territory          443        443     443
               Diamond Princess cruise ship           12         12      12
               External territories                    1          1       1
               From Diamond Princess                  18         18      18
               Jervis Bay Territory                    1          1       1
...                                                  ...        ...     ...
Ukraine        Vinnytsia Oblast                      363        363     363
               Volyn Oblast                          363        363     363
               Zakarpattia Oblast                    363        363     363
               Zaporizhia Oblast                     363        363     363
               Zhytomyr Oblast                       363        363     363

                                             Recovered
Country/Region Province/State
Australia      Australian Capital Territory        443
               Diamond Princess cruise ship         12
               External territories                  1
               From Diamond Princess                18
               Jervis Bay Territory                  1
...                                                ...
Ukraine        Vinnytsia Oblast                    363
               Volyn Oblast                        363
               Zakarpattia Oblast                  363
               Zaporizhia Oblast                   363
               Zhytomyr Oblast                     363

[759 rows x 6 columns]

### 4.7.3 Split-apply-combine

![](../img/split_apply_combine.png)
**This method of splitting your dataset in smaller groups and then applying an operation 
(such as min or max) to get aggregate result is called Split-Apply-Combine. It is illustrated in a diagram below**

In [38]:
df = pd.read_csv("../data/LungCapData.csv")
df

     LungCap  Age  Height Smoke  Gender Caesarean
0      6.475    6    62.1    no    male        no
1     10.125   18    74.7   yes  female        no
2      9.550   16    69.7    no  female       yes
3     11.125   14    71.0    no    male        no
4      4.800    5    56.9    no    male        no
..       ...  ...     ...   ...     ...       ...
720    5.725    9    56.0    no  female        no
721    9.050   18    72.0   yes    male       yes
722    3.850   11    60.5   yes  female        no
723    9.825   15    64.9    no  female        no
724    7.100   10    67.7    no    male        no

[725 rows x 6 columns]

In [45]:
# group by "Gender" then find average of age in each group
average_age_by_gender = df.groupby('Gender')["Age"].mean()
average_age_by_gender

Gender
female    12.449721
male      12.207084
Name: Age, dtype: float64

In [47]:
# group by gender and find max of "LungCap" and "Age" column
max_lungCap_age_each_gender = df.groupby("Gender")[["LungCap", "Age"]].max() 
max_lungCap_age_each_gender

        LungCap  Age
Gender
female   13.075   19
male     14.675   19

### 4.7.4 Advanced Aggregation with `agg()`

In [48]:
df = pd.read_table("../data/pulse.txt")

In [49]:
df.head()

,Height,Weight,Age,Gender,Smokes,Alcohol,Exercise,Ran,Pulse1,Pulse2,Year
0,173,57.0,18,2,2,1,2,2,86.0,88.0,93
1,179,58.0,19,2,2,1,2,1,82.0,150.0,93
2,167,62.0,18,2,2,1,1,1,96.0,176.0,93
3,195,84.0,18,1,2,1,1,2,71.0,73.0,93
4,173,64.0,18,2,2,1,3,2,90.0,88.0,93

In [50]:
group_by_exercise_and_average_all_columns = df.groupby("Exercise").mean()
group_by_exercise_and_average_all_columns

,Height,Weight,Age,Gender,Smokes,Alcohol,Ran,Pulse1,Pulse2,Year
Exercise,,,,,,,,,,
1,177.857143,71.571429,19.571429,1.214286,2.000000,1.071429,1.500000,68.642857,93.642857,95.428571
2,173.913793,67.810345,20.534483,1.482759,1.896552,1.362069,1.586207,75.473684,96.771930,95.465517
3,170.444444,63.097222,21.083333,1.527778,1.861111,1.500000,1.611111,77.222222,96.333333,95.833333

In [51]:
group_by_exercise_find_all_statistics = df.groupby("Gender").agg(["min", "max", "mean", "median", "std"])
group_by_exercise_find_all_statistics

       Height                                   Weight                    \
          min  max        mean median       std    min    max       mean
Gender
1         167  195  179.603448  180.0  7.393548   53.0  110.0  74.948276
2         140  180  165.920000  165.0  7.583118   41.0   78.0  57.190000

                          ... Pulse2                                     Year  \
       median        std  ...    min    max       mean median        std  min
Gender                    ...
1        73.5  14.201770  ...   56.0  168.0  94.293103   82.0  32.555490   93
2        56.5   8.453287  ...   59.0  176.0  98.489796   88.0  30.493935   93


       max       mean median       std
Gender
1       98  95.586207   96.0  1.727329
2       98  95.580000   96.0  1.773846

[2 rows x 50 columns]

In [53]:
# group by "gender" find basic statistics on "Height" and "Weight" column
group_gender_find_stat_on_height_weight =  df.groupby("Gender").agg({"Height": ["min", "max", "mean", "median", "std"],
                                          "Weight": ["min", "max", "mean", "median", "std"]})
group_gender_find_stat_on_height_weight

       Height                                   Weight                    \
          min  max        mean median       std    min    max       mean
Gender
1         167  195  179.603448  180.0  7.393548   53.0  110.0  74.948276
2         140  180  165.920000  165.0  7.583118   41.0   78.0  57.190000


       median        std
Gender
1        73.5  14.201770
2        56.5   8.453287

### 4.7.5 GroupBy Aggregation with Relabeling